name: assetnote/kiterunner

on:
  push:
    branches:
      - main  # Change to your default branch if not main
    paths:
      - '.github/workflows/kiterunner.yml'
      - 'files/kiterunner/**'
permissions:
  contents: read
  packages: write
  security-events: write

env:
  RELEASE_VERSION: "v1.0.2"
  KR_DIR: "/usr/local/kiterunner"

jobs:
  build-and-push-amd64:
    runs-on: ubuntu-latest  # Native amd64 GitHub runner
    steps:        
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.build-cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 \
            --build-arg "KR_DIR=${{ env.KR_DIR }}" --build-arg "RELEASE_VERSION=${{ env.RELEASE_VERSION }}" \
            --tag ghcr.io/${{ github.repository_owner }}/kiterunner:${{ env.RELEASE_VERSION }}-amd64 \
            --tag ghcr.io/${{ github.repository_owner }}/kiterunner:latest-amd64 ./files/kiterunner
            docker push ghcr.io/${{ github.repository_owner }}/kiterunner:${{ env.RELEASE_VERSION }}-amd64
            docker push ghcr.io/${{ github.repository_owner }}/kiterunner:latest-amd64
      
      - name: Logout from Docker Hub
        run: docker logout

  build-and-push-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push arm64 Docker image
        run: |
          docker build --platform linux/arm64 \
            --build-arg "KR_DIR=${{ env.KR_DIR }}" --build-arg "RELEASE_VERSION=${{ env.RELEASE_VERSION }}" \
            --tag ghcr.io/${{ github.repository_owner }}/kiterunner:${{ env.RELEASE_VERSION }}-arm64 \
            --tag ghcr.io/${{ github.repository_owner }}/kiterunner:latest-arm64 ./files/kiterunner
          docker push ghcr.io/${{ github.repository_owner }}/kiterunner:${{ env.RELEASE_VERSION }}-arm64
          docker push ghcr.io/${{ github.repository_owner }}/kiterunner:latest-arm64

      - name: Logout from Docker Hub
        run: docker logout

  create-multiarch-manifest:
    needs: [build-and-push-amd64, build-and-push-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-platform manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository_owner }}/kiterunner:${{ env.RELEASE_VERSION }} \
            --amend ghcr.io/${{ github.repository_owner }}/kiterunner:${{ env.RELEASE_VERSION }}-amd64 \
            --amend ghcr.io/${{ github.repository_owner }}/kiterunner:${{ env.RELEASE_VERSION }}-arm64
          
          docker manifest create ghcr.io/${{ github.repository_owner }}/kiterunner:latest \
            --amend ghcr.io/${{ github.repository_owner }}/kiterunner:latest-amd64 \
            --amend ghcr.io/${{ github.repository_owner }}/kiterunner:latest-arm64
          
          docker manifest push ghcr.io/${{ github.repository_owner }}/kiterunner:${{ env.RELEASE_VERSION }}
          docker manifest push ghcr.io/${{ github.repository_owner }}/kiterunner:latest

  security-scan:
    needs: create-multiarch-manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check ghcr.io/${{ github.repository_owner }}/kiterunner:${{ env.RELEASE_VERSION }} image
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/${{ github.repository_owner }}/kiterunner:${{ env.RELEASE_VERSION }}
          args: --file=./files/kiterunner/Dockerfile
          json: true
      - uses: garethr/snyk-to-sarif@master
      - uses: actions/upload-artifact@v4
        with:
          name: SARIF
          path: snyk.sarif
      
      - name: Upload SARIF Report to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  sonarcloud-kiterunner:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      # Checkout the kiterunner  repository
      - name: Checkout kiterunner Repository
        uses: actions/checkout@v4
        with:
          repository: assetnote/kiterunner
          path: kiterunner  # Optional: Clone into a specific directory
          ref: ${{ env.RELEASE_VERSION }}

      # Install dependencies
      - name: Install dependencies
        run: |
          cd kiterunner
          sudo apt update && sudo apt install -y \
            build-essential \
            git \
            autoconf \
            automake \
            libtool-bin \
            pkg-config \
            libcurl4-openssl-dev \
            libusb-1.0-0-dev \
            libssl-dev \
            udev \
            && sudo rm -rf /var/lib/apt/lists/*
            
      # SonarCloud Scan
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v6.0.0
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=matusso
            -Dsonar.projectKey=docker-builds:kiterunner
            -Dsonar.verbose=true
            -Dsonar.projectName=kiterunner
            -Dsonar.sources=kiterunner