name: SonarCloud Scan - Metasploit Framework

on:
  push:
    branches:
      - sonarcloud-integration
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud-metasploit:
    name: Scan Metasploit Framework
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Metasploit Framework Repository
        uses: actions/checkout@v4
        with:
          repository: rapid7/metasploit-framework
          path: metasploit-framework  # Optional: Clone into a specific directory
          ref: '6.4.38'

      - name: Install libpcap
        run: sudo apt update && sudo apt install -y libpcap-dev
      
      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.5' # Adjust to required version
          bundler-cache: true

      # Install Ruby dependencies
      - name: Install Ruby dependencies
        run: |
          cd metasploit-framework
          bundle install --path vendor/bundle

      # SonarCloud Scan for Metasploit Framework
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v4
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=matusso
            -Dsonar.projectKey=docker-builds:metasploit-framework
            -Dsonar.verbose=true
            -Dsonar.projectName=metasploit-framework
            -Dsonar.languages=ruby
            -Dsonar.sources=metasploit-framework
            -Dsonar.exclusions=**/*.java,**/*.c,**/*.cpp,**/*.h,**/*.mm,**/*.m
            -Dsonar.c.file.suffixes=-
            -Dsonar.cpp.file.suffixes=-
            -Dsonar.objc.file.suffixes=-
