name: Build and Push mvt-project/mvt to burso/mvt

on:
  push:
    branches:
      - main  # Change to your default branch if not main
  pull_request:
    branches:
      - main  # Change to your default branch if not main

permissions:
  contents: read
  security-events: write

jobs:
  build-and-push:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master

      - name: Set release version
        id: set_version
        run: echo "RELEASE_VERSION=v2.5.4" >> $GITHUB_ENV

      - name: Clone mvt-project/mvt repository at specific version
        run: |
          git clone --branch ${{ env.RELEASE_VERSION }} https://github.com/mvt-project/mvt.git

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        run: |
          docker buildx build --push \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/mvt:${{ env.RELEASE_VERSION }} \
            --platform linux/amd64,linux/arm64 ./mvt

      - name: Logout from Docker Hub
        run: docker logout
      
      - name: Check ${{ secrets.DOCKER_HUB_USERNAME }}/mvt:${{ env.RELEASE_VERSION }} image
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/mvt:${{ env.RELEASE_VERSION }}
          args: --file=./mvt/Dockerfile
          json: true
      - uses: garethr/snyk-to-sarif@master
      - uses: actions/upload-artifact@v4
        with:
          name: SARIF
          path: snyk.sarif
      
      - name: Upload SARIF Report to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          